apiVersion: v1
kind: Service
metadata:
  name: simrunner
  labels:
    app: simrunner
spec:
  type: ClusterIP
  selector:
    app: simrunner
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
